import type { Metadata } from "next";
import { inter } from "@/app/fonts";
import { spaceGrotesk } from "@/app/fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "SplitShifts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"className={spaceGrotesk.variable}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
