import type { Metadata } from "next";
import { inter } from "@/app/components/ui/fonts";
import { spaceGrotesk } from "@/app/components/ui/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "SplitShifts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${inter.variable} ${spaceGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
